
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 27 11:17:38 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 16;
  public static final int CHAR = 40;
  public static final int CONST = 13;
  public static final int LPAREN = 6;
  public static final int GREATER = 34;
  public static final int SEMI = 5;
  public static final int CONTINUE = 19;
  public static final int MINUS = 28;
  public static final int RPAREN = 7;
  public static final int AND = 24;
  public static final int OR = 23;
  public static final int COMMA = 10;
  public static final int DIV = 30;
  public static final int DIFFERENT = 33;
  public static final int LESSER = 36;
  public static final int PLUS = 27;
  public static final int IF = 17;
  public static final int BOOLEAN = 39;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 15;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NUMBER = 41;
  public static final int ELESSER = 37;
  public static final int EGREATER = 35;
  public static final int MOD = 31;
  public static final int IDENT = 38;
  public static final int BREAK = 22;
  public static final int VOID = 12;
  public static final int SAME = 32;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int LSQUARE = 25;
  public static final int READ = 20;
  public static final int RSQUARE = 26;
  public static final int WHILE = 21;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int PRINT = 11;
}

